name = "maku-jannu"
author = "maku-jannu-admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c992f33503a71d0df42db1077206e98b8b23cabd300a98b8c76cbd69ba7ebeed"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
