name = "maku-jannu"
author = "maku-jannu-admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe8fa447a1ce133150f81e7535e1e9e5529291e7f0ff849482af72a13cd6490"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
