name = "maku-jannu"
author = "maku-jannu-admin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff0a3fc82cbaa00311e54749a562903198dc86bb74021bfd981091ab946ddfd"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
